apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-deploy
  labels:
    app: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-gateway
  template:
    metadata:
      labels:
        app: payment-gateway
    spec:
      containers:
      - name: payment-gateway
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "50Mi"
